#构建命令 docker build -t lzwing/jenkins:0.0.1 .

FROM centos:7
MAINTAINER lzwing "chenzhongyong@cecdat.com"

#安装wget
RUN yum install wget -y

#安装JDK
RUN mkdir /var/tmp/jdk
RUN wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie"  -P /var/tmp/jdk http://download.oracle.com/otn-pub/java/jdk/8u152-b16/aa0333dd3019491ca4f6ddbe78cdb6d0/jdk-8u152-linux-x64.tar.gz
RUN tar xzf /var/tmp/jdk/jdk-8u152-linux-x64.tar.gz -C /var/tmp/jdk
RUN rm -rf /var/tmp/jdk/jdk-8u152-linux-x64.tar.gz

#安装tomcat
#RUN mkdir /var/tmp/tomcat
#RUN wget -P /var/tmp/tomcat http://mirrors.hust.edu.cn/apache/tomcat/tomcat-8/v8.5.8/bin/apache-tomcat-8.5.8.tar.gz
#RUN tar xzf /var/tmp/tomcat/apache-tomcat-8.5.8.tar.gz -C /var/tmp/tomcat
#RUN rm -rf /var/tmp/tomcat/apache-tomcat-8.5.8.tar.gz

#安装maven
RUN mkdir /var/tmp/maven
RUN wget -P /var/tmp/maven  http://mirrors.tuna.tsinghua.edu.cn/apache/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
RUN tar xzf /var/tmp/maven/apache-maven-3.5.2-bin.tar.gz -C /var/tmp/maven
RUN rm -rf /var/tmp/maven/apache-maven-3.5.2-bin.tar.gz

#安装git环境
RUN yum install git -y

#安装jenkins
RUN mkdir -p  /var/jenkins_home
RUN wget -P /usr/share/jenkins http://mirrors.jenkins-ci.org/war/latest/jenkins.war

#设置环境变量
ENV JAVA_HOME /var/tmp/jdk/jdk1.8.0_152
#ENV CATALINA_HOME /var/tmp/tomcat/apache-tomcat-8.5.8
ENV M2_HOME /var/tmp/maven/apache-maven-3.3.9
ENV JENKINS_HOME /var/jenkins_home
ENV PATH $PATH:$JAVA_HOME/bin:$CATALINA_HOME/bin:$M2_HOME/bin




#打包项目并拷贝到tomcat webapps目录
#RUN mkdir /var/tmp/webapp
#ADD ./ /var/tmp/webapp
#RUN cd /var/tmp/webapp && mvn package && cp /var/tmp/webapp/target/CIJD.war /var/tmp/tomcat/apache-tomcat-8.5.8/webapps


#开启内部服务端口
EXPOSE 8080

#启动tomcat服务器
#CMD ["./var/tmp/tomcat/apache-tomcat-8.5.8/bin/catalina.sh","run"]
CMD ["java",  "-jar",  "/usr/share/jenkins/jenkins.war"]